name: Fulfill Shared Protofiles
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip Folder
      run: zip -r fulfill-proto.zip /fulfill/services/shared-protobuf/proto-api
    - name: Release to Github
      run: echo "Release"
   # - name: Bump version and push tag
   #   uses: anothrNick/github-tag-action@master
   #   env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #     REPO_OWNER: abdullah.elzayany